title: Pixella Chatbot Docs
description: Documentation for Pixella Chatbot
highlighter: rouge
rouge:
  theme: github

markdown: kramdown
theme: null   # IMPORTANT
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Ensure custom CSS and favicon loads
include:
  - _layouts
  - _includes
  - assets

baseurl: ""
url: ""

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
